services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: email-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - web
    ports:
      - "3000:3000"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    depends_on:
      - app
      - server

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: 