FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4200

# Start the application in development mode with host set to 0.0.0.0 to allow external access
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"] 